// Code generated by "stringer -linecomment -type=MergeKind -output=merge_kind_string.go"; DO NOT EDIT.

package github

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MergeInvalid-0]
	_ = x[Squash-1]
	_ = x[MergeCommit-2]
	_ = x[Rebase-3]
}

const _MergeKind_name = "unknownSquash and MergeMerge CommitRebase and Merge"

var _MergeKind_index = [...]uint8{0, 7, 23, 35, 51}

func (i MergeKind) String() string {
	if i >= MergeKind(len(_MergeKind_index)-1) {
		return "MergeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MergeKind_name[_MergeKind_index[i]:_MergeKind_index[i+1]]
}
