name: Go

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install Dependencies
        run: go mod download

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -race -v './...'

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Vet
        run: go vet './...'

      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: -E gosec

      - name: Go mod tidy
        run: |
          go mod tidy >/dev/null || exit 1
          if ! diff="$(git diff -U1 --color --exit-code)"; then
            echo "go.mod and/or go.sum are not up to date. Please run 'go mod tidy' and commit the changes."
            echo "$diff"
            git checkout -- .
            exit 1
          else
            echo "go.mod and go.sum are up to date."
          fi

  vulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check Go Vulnerabilities
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: 'go.mod'
